# Generated by Django 4.0.6 on 2022-08-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audiobooks',
        ),
        migrations.DeleteModel(
            name='Ebooks',
        ),
    ]
