# Generated by Django 4.0.6 on 2022-08-15 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_audiobooks_ebooks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audiobooks',
        ),
        migrations.DeleteModel(
            name='Ebooks',
        ),
    ]
