# Generated by Django 4.0.6 on 2022-08-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_delete_audiobooks_delete_ebooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('book_genre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ebooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('book_genre', models.CharField(max_length=40)),
            ],
        ),
    ]
